### ISSUE TITLE
Error in LibMayronDB

### ISSUE THREAD

**Issue by Trockenbrot** [unitedgamereu/mayronui-gen5-bfa#4]
An error in the LibMayronDB occured.

Source / Action / Trigger: unknown

Error:
`Message: Interface\AddOns\MUI_Core\libs/LibMayronDB.lua:495: attempt to concatenate local 'key' (a nil value)
Time: Wed Jul 25 13:46:09 2018
Count: 1
Stack: Interface\AddOns\MUI_Core\libs/LibMayronDB.lua:495: attempt to concatenate local 'key' (a nil value)
Interface\AddOns\MUI_Core\libs/LibMayronDB.lua:495: in function <Interface\AddOns\MUI_Core\libs/LibMayronDB.lua:485>
Interface\AddOns\MUI_Core\data_text.lua:570: in function <Interface\AddOns\MUI_Core\data_text.lua:565>
(tail call): ?
Interface\AddOns\MUI_Core\APIs/event_manager.lua:69: in function <Interface\AddOns\MUI_Core\APIs/event_manager.lua:64>
(tail call): ?
Interface\AddOns\MUI_Core\APIs/event_manager.lua:156: in function `CallHandlers'
Interface\AddOns\MUI_Core\APIs/event_manager.lua:148: in function <Interface\AddOns\MUI_Core\APIs/event_manager.lua:147>

Locals: self = <table> {
 _data = <table> {
 }
}
key = nil
data = <table> {
 db = <table> {
 }
 path = "datatext.spec.sets"
 tbl_type = "profile"
}
(*temporary) = "datatext.spec.sets."
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to concatenate local 'key' (a nil value)"
Observer = <table> {
 metatable = <table> {
 }
 GetTable = <function> defined @Interface\AddOns\MUI_Core\libs/LibMayronDB.lua:387
 Iterate = <function> defined @Interface\AddOns\MUI_Core\libs/LibMayronDB.lua:412
 GetParent = <function> defined @Interface\AddOns\MUI_Core\libs/LibMayronDB.lua:354
 Print = <function> defined @Interface\AddOns\MUI_Core\libs/LibMayronDB.lua:468
 Remove = <function> defined @Interface\AddOns\MUI_Core\libs/LibMayronDB.lua:434
 HasParent = <function> defined @Interface\AddOns\MUI_Core\libs/LibMayronDB.lua:361
 GetLength = <function> defined @Interface\AddOns\MUI_Core\libs/LibMayronDB.lua:420
 SetParent = <function> defined @Interface\AddOns\MUI_Core\libs/LibMayronDB.lua:344
 new = <function> defined @Interface\AddOns\MUI_Core\libs/LibMayronDB.lua:632
}
rawget = <function> defined =[C]:-1
private = <table> {
 GetNewProfileName = <function> defined @Interface\AddOns\MUI_Core\libs/LibMayronDB.lua:667
 IterateArgs = <function> defined @Interface\AddOns\MUI_Core\libs/LibMayronDB.lua:805
 PrintTable = <function> defined @Interface\AddOns\MUI_Core\libs/LibMayronDB.lua:763
 RunCleaner = <function> defined @Interface\AddOns\MUI_Core\libs/LibMayronDB.lua:966
 db_info = <table> {
 }
 GetSVTable = <function> defined @Interface\AddOns\MUI_Core\libs/LibMayronDB.lua:717
 GetDatabaseInfo = <function> defined @Interface\AddOns\MUI_Core\libs/LibMayronDB.lua:956
 EmptyTable = <function> defined @Interface\AddOns\MUI_Core\libs/LibMayronDB.lua:886
 GetLastTableKeyPairs = <function> defined @Interface\AddOns\MUI_Core\libs/LibMayronDB.lua:917
 StartDatabase = <function> defined @Interface\AddOns\MUI_Core\libs/LibMayronDB.lua:685
 GetTable = <function> defined @Interface\AddOns\MUI_Core\libs/LibMayronDB.lua:869
 GetTableSize = <function> defined @Interface\AddOns\MUI_Core\libs/LibMayronDB.lua:893
 GetWrapper = <function> defined @Interface\AddOns\MUI_Core\libs/LibMayronDB.lua:849
 GetNextParentValue = <function> defined @Interface\AddOns\MUI_Core\libs/LibMayronDB.lua:737
}
type = <function> defined =[C]:-1
`

**Comment by DGMonster** [comment]
Message: Interface\AddOns\MUI_Core\libs/LibMayronDB.lua:495: attempt to concatenate local 'key' (a nil value)
Time: Wed Jul 25 18:45:20 2018
Count: 1
Stack: Interface\AddOns\MUI_Core\libs/LibMayronDB.lua:495: attempt to concatenate local 'key' (a nil value)
Interface\AddOns\MUI_Core\libs/LibMayronDB.lua:495: in function <Interface\AddOns\MUI_Core\libs/LibMayronDB.lua:485>
Interface\AddOns\MUI_Core\data_text.lua:570: in function <Interface\AddOns\MUI_Core\data_text.lua:565>
(tail call): ?
Interface\AddOns\MUI_Core\APIs/event_manager.lua:69: in function <Interface\AddOns\MUI_Core\APIs/event_manager.lua:64>
(tail call): ?
Interface\AddOns\MUI_Core\APIs/event_manager.lua:156: in function `CallHandlers'
Interface\AddOns\MUI_Core\APIs/event_manager.lua:148: in function <Interface\AddOns\MUI_Core\APIs/event_manager.lua:147>

Locals: self = <table> {
 _data = <table> {
 }
}
key = nil
data = <table> {
 db = <table> {
 }
 path = "datatext.spec.sets"
 tbl_type = "profile"
}
(*temporary) = "datatext.spec.sets."
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to concatenate local 'key' (a nil value)"
Observer = <table> {
 metatable = <table> {
 }
 GetTable = <function> defined @Interface\AddOns\MUI_Core\libs/LibMayronDB.lua:387
 Iterate = <function> defined @Interface\AddOns\MUI_Core\libs/LibMayronDB.lua:412
 GetParent = <function> defined @Interface\AddOns\MUI_Core\libs/LibMayronDB.lua:354
 Print = <function> defined @Interface\AddOns\MUI_Core\libs/LibMayronDB.lua:468
 Remove = <function> defined @Interface\AddOns\MUI_Core\libs/LibMayronDB.lua:434
 HasParent = <function> defined @Interface\AddOns\MUI_Core\libs/LibMayronDB.lua:361
 GetLength = <function> defined @Interface\AddOns\MUI_Core\libs/LibMayronDB.lua:420
 SetParent = <function> defined @Interface\AddOns\MUI_Core\libs/LibMayronDB.lua:344
 new = <function> defined @Interface\AddOns\MUI_Core\libs/LibMayronDB.lua:632
}
rawget = <function> defined =[C]:-1
private = <table> {
 GetNewProfileName = <function> defined @Interface\AddOns\MUI_Core\libs/LibMayronDB.lua:667
 IterateArgs = <function> defined @Interface\AddOns\MUI_Core\libs/LibMayronDB.lua:805
 PrintTable = <function> defined @Interface\AddOns\MUI_Core\libs/LibMayronDB.lua:763
 RunCleaner = <function> defined @Interface\AddOns\MUI_Core\libs/LibMayronDB.lua:966
 db_info = <table> {
 }
 GetSVTable = <function> defined @Interface\AddOns\MUI_Core\libs/LibMayronDB.lua:717
 GetDatabaseInfo = <function> defined @Interface\AddOns\MUI_Core\libs/LibMayronDB.lua:956
 EmptyTable = <function> defined @Interface\AddOns\MUI_Core\libs/LibMayronDB.lua:886
 GetLastTableKeyPairs = <function> defined @Interface\AddOns\MUI_Core\libs/LibMayronDB.lua:917
 StartDatabase = <function> defined @Interface\AddOns\MUI_Core\libs/LibMayronDB.lua:685
 GetTable = <function> defined @Interface\AddOns\MUI_Core\libs/LibMayronDB.lua:869
 GetTableSize = <function> defined @Interface\AddOns\MUI_Core\libs/LibMayronDB.lua:893
 GetWrapper = <function> defined @Interface\AddOns\MUI_Core\libs/LibMayronDB.lua:849
 GetNextParentValue = <function> defined @Interface\AddOns\MUI_Core\libs/LibMayronDB.lua:737
}
type = <function> defined =[C]:-1
